CREATE TABLE IF NOT EXISTS message (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    node_id TEXT NOT NULL,
    target TEXT NOT NULL,
    type TEXT NOT NULL,
    data TEXT NOT NULL,
    served INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS node (
    node_id TEXT NOT NULL PRIMARY KEY,
    node_type TEXT NOT NULL,
    ip TEXT NOT NULL,
    port INTEGER NOT NULL,
    pk TEXT,
    last_active TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    node_id TEXT NOT NULL,
    node_type TEXT NOT NULL,
    node_position TEXT NOT NULL,
    timecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
